### ISSUE TITLE
Historical data before there should be any on a number of tickers

### ISSUE THREAD

**Issue by christian-storm** [polygon-io/issues#100]
**URL**
'https://api.polygon.io/v2/aggs/ticker/ACV/range/1/day/2011-05-09/2015-05-24?unadjusted=False&apiKey=XXXXXXX'

**Result**
The ticker ACV started trading on 2015-05-22 but the request returns data before the first day of trading.

**Expected Result**
One bar's worth of data for 2015-05-22.  Instead, I got data for 2011-05-09 and 2011-05-22 as well.

**Additional context**
If I set the from/start date to much earlier, I see that the erroneous data starts at 2003-10-01.  Strangely, I see the same erroneous start date for other symbols, e.g., CHY.

**Comment by jrbell19** [comment]
Hi there, 

This is because this ticker was previously traded under the company 'Alberto Culver Company' until a merger with Unilever on May 10, 2011. 

AllianzGI Diversified Income & Convertible Fund did not begin trading until 2015-05-22. 

Hope this clears things up. We are working to track these types of corporate actions to eliminate further confusion.
