### ISSUE TITLE
Missing pricing data for 2 equities that exist in reference

### ISSUE THREAD

**Issue by cnaccio** [polygon-io/issues#120]
**URL**
https://api.polygon.io/v2/aggs/ticker/STRR/range/1/day/2020-01-01/2020-12-31?unadjusted=true&sort=asc&limit=120
https://api.polygon.io/v2/aggs/ticker/PFX/range/1/day/2020-01-01/2020-12-31?unadjusted=true&sort=asc&limit=120

**Result**
No aggregate bars are returned

**Expected Result**
Expect pricing data to be returned as both these tickers are available in the reference api. You can easily pull up these names using TradingView or any other charting software and see that both have been active for some time. 

Here's are the reference api urls:
https://api.polygon.io/v2/reference/tickers?sort=ticker&search=STRR
https://api.polygon.io/v2/reference/tickers?sort=ticker&search=PFX

**Comment by jrbell19** [comment]
Hi there, 

Both of these instances are related to ticker changes due to an acquisition. 

STRR - https://www.globenewswire.com/news-release/2020/12/28/2150994/0/en/Digirad-Corporation-Changes-Corporate-Name-to-Star-Equity-Holdings-Inc.html

PFX - https://www.nasdaqtrader.com/TraderNews.aspx?id=dtn2020-54

We are working on a solution that will solve this type of confusion.
