### ISSUE TITLE
Aggregates: Hourly highs above daily highs

### ISSUE THREAD

**Issue by d-e-s-o** [polygon-io/issues#123]
**URL**
GET https://api.polygon.io/v2/aggs/ticker/VMW/range/1/day/2021-02-03/2021-02-03

**Result**
```json
{"v":634172,"vw":142.8428,"o":144.02,"c":142.34,"h":144.03,"l":142.07,"t":1612328400000}
```

As you can see, the high price on 2021-02-03 is 144.03. Yet, when I retrieve hour or minute aggregates, I can clearly see that the price was at or above 145 at some point:

GET https://api.polygon.io/v2/aggs/ticker/VMW/range/1/hour/2021-02-03/2021-02-03
```json
[{"..."}, {"v":156849,"vw":144.1122,"o":144.89,"c":143.62,"h":145.11,"l":143.01,"t":1612364400000,"n":3142}, {"..."}]
```

And there I was, thinking that a daily high would be the maximum value over the course of the day and not just the result of a roll of a dice. What is going on here?

**Comment by jrbell19** [comment]
Hi there, 

Apologies for the radio silence on this issue. It looks like this was fixed by one of our recent aggregates updates. If you query the data now, you will see the high value of the daily aggregate is reflected within that minutes OHLC.

https://api.polygon.io/v2/aggs/ticker/VMW/range/1/hour/2021-02-03/2021-02-03?apikey=

{
     v: 156849,
     vw: 144.1122,
     o: 144.89,
     c: 143.62,
     h: 145.11, <<<
     l: 143.01,
     t: 1612364400000,
     n: 3142
}

https://api.polygon.io/v2/aggs/ticker/VMW/range/1/day/2021-02-03/2021-02-03?apikey=

{
     v: 1223074,
     vw: 143.396,
     o: 143.2,
     c: 142.34,
     h: 145.11, <<<
     l: 142.07,
     t: 1612328400000,
     n: 16974
}

Closing this issue. Please let me know if you see anything else out of the ordinary.
