### ISSUE TITLE
1 to 1 splits in v3 split API

### ISSUE THREAD

**Issue by bluelu** [polygon-io/issues#189]
Hi,

Can I safely ignore 1 -> 1 splits? They were not present in the v2 API.

Example:
Query: /v3/reference/splits?ticker=AFL 
Contains entry: {"execution_date":"2018-03-16","split_from":1,"split_to":1,"ticker":"AFL"}

Thanks
Thibaut

**Comment by jrbell19** [comment]
We're currently looking into this now. Apologies for the confusion.

**Comment by jrbell19** [comment]
It turns out, this is a special case. In this instance, the split is a stock dividend payout. So for every one share owned, the owner gets an additional share. And the share price doesn't change. 

It is safe to ignore these on your end, while we figure out a better way to handle this situation. Apologies for the confusion.
