### ISSUE TITLE
Minute aggregates vw price sometimes is lower/higher than low/high

### ISSUE THREAD

**Issue by smartFunX** [polygon-io/issues#205]
**URL**
https://api.polygon.io/v2/aggs/ticker/SPY/range/1/minute/2022-03-23/2022-03-23

**Result**
One of the returned aggregates looks as following:
{"v":325698,"vw":448.4448,"a":446.8876,"o":445.02,"c":444.92,"h":445.1,"l":444.92,"t":1648059240000,"n":805,"op":446.91}

**Expected Result**
I'm expecting "vw" price to be within "l" "h" ranges, but here we see that it is significantly higher than "h".
I noticed that it is happening several times during a day (roughly ~ 10 times)

**Desktop (please complete the following information):**
 - OS: Mac OS
It happens in Chrome browser as well as in the API calls in Python.

**Comment by clickingbuttons** [comment]
Whenever we update volume according to the [CTA (page 67)](https://www.nyse.com/publicdocs/ctaplan/notifications/trader-update/cts_output_spec.pdf) and [UTP (page 43)](https://www.utpplan.com/DOC/UtpBinaryOutputSpec.pdf) specs we update VWAP (which is "vw").

Since some trades that don't update high/low (like odd lots) do update volume you can see a VWAP outside of high/low bounds. Sadly VWAP is not standardized for aggregates by the CTA/UTP spec. We're open to changing "last" to be the updating condition but it'd be breaking for now.

If you want "vw" to always be between high/low you can aggregate our [trades v3 API](https://polygon.io/docs/stocks/get_v3_trades__stockticker) using the "last" condition. If you want a more accurate VWAP you can ignore conditions altogether but they will likely be outside the bounds of your aggs.

**Comment by smartFunX** [comment]
Odd lots supposed to be of a lower volume compared to the rest of lots. In the example I shared the odd lot volume moves the vw by 0.75% compared to the high price for that minute, which is very significant. Also it is SPY ETF that shouldn't be that much affected by odd lots?

**Comment by clickingbuttons** [comment]
> Odd lots supposed to be of a lower volume compared to the rest of lots.

In practice this isn't always the case. The SEC has a study that [shows odd lot trades for the top decile of stocks contribute to 22% of the total volume.](https://www.sec.gov/marketstructure/datavis/ma_stocks_oddlotvolume.html)

> Also it is SPY ETF that shouldn't be that much affected by odd lots?

It's not just odd lot trades that update volume but not high/low. It's also these conditions:
- Bunched Sold Trades
- Price Variation Trade
- Next Day
- Seller
- Form T
- Extended trading hours (Sold Out of Sequence)
- Contingent Trade
- Average Price Trade
- Qualified Contingent Trade (“QCT”)
