### ISSUE TITLE
Pagination issue with option snapshot API

### ISSUE THREAD

**Issue by yongqli** [polygon-io/issues#237]
**URL**
https://api.polygon.io/v3/snapshot/options/SPX?expiration_date=2023-03-10&limit=250

**Result**
Extra results for other expiries are returned in subsequent pages.

**Expected Result**
Only the `2023-03-10` expiry is returned.

**Comment by jrbell19** [comment]
@yongqli Because you've passed in the ?expiration_date= parameter with 2023-03-10 set, the results returned will only be for contracts with that expiration date. 

If you're looking for all the contracts after that date, you could pass in the .gte extension and the sort parameter to paginate through additional expiration dates. Here's an example:

https://api.polygon.io/v3/snapshot/options/SPX?expiration_date.gte=2023-03-10&sort=expiration_date&apiKey=*

**Comment by jrbell19** [comment]
i've realized that I misunderstood the issue here. This is a known issue, and something that we are currently working to address. Apologies for the confusion. 

I will circle back once this is resolved

**Comment by jrbell19** [comment]
This should be resolved now. Please let us know if you continue to have trouble.
