### ISSUE TITLE
Divs - declaration_date == today always returns zero result

### ISSUE THREAD

**Issue by mpolatov** [polygon-io/issues#296]
**URL**
https://api.polygon.io/v3/reference/dividends?declaration_date=2024-04-09&apiKey=_

**Result**
{
    "results": [],
    "status": "OK",
    "request_id": "ca33690c2137dfc8ca6c67815955aeef"
}

**Expected Result**
Divs scheduled for today

When I query past days or *the previous day* - all works just fine.

**Comment by AHangstefer** [comment]
Hello again! I am seeing dividends listed for the current date:
https://api.polygon.io/v3/reference/dividends?ex_dividend_date=2024-04-12&apiKey=**
We recently implemented an additional data source for our dividend data. It's likely that it didn't return anything before because we were transitioning from our original source to the additional sources.

**Comment by mpolatov** [comment]
Your query is different from mine - I want to see what div is *declared* today or on a given day - hence my declaration_date filter.
It still returns empty for the whole this week actually.

**Comment by mpolatov** [comment]
div query by declaration_date was broken since 04/08 - last date to return any data was 04/05.
