### ISSUE TITLE
Flat files in S3 are not split adjusted

### ISSUE THREAD

**Issue by cookie359** [polygon-io/issues#321]
Doing some sanity checks on the data after downloading and importing daily files.

TSLA splits in 2020 and 2022 can clearly be seen.

Couldn't find anything in the docs that explicitly says that they should be split adjusted but would assume most people would want them to be to simplify backtesting?

![Screenshot 2024-10-25 095639](https://github.com/user-attachments/assets/af606fc8-aa19-4ac9-8e10-42506ea1c165)

![Screenshot 2024-10-25 095514](https://github.com/user-attachments/assets/fe8e4d6e-76e4-49c4-bd2d-238bd14c4d58)

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. Our flat files are not split adjusted and that is intentional. If you're interested in split adjusted flat files, you can submit that idea through our [roadmap](https://polygon.io/product-roadmap)! Users can vote on what's most important to them and we use that data to help us decide what features to work on next.
