### ISSUE TITLE
Accumulated Volume From 1 Minute Bars Does Not Match Daily Open/Close Volume

### ISSUE THREAD

**Issue by neoform** [polygon-io/issues#70]
**URL**
https://api.polygon.io/v1/open-close/MSFT/2020-08-21?apiKey=XXXXXX
https://api.polygon.io/v2/aggs/ticker/MSFT/range/1/MINUTE/2020-08-21/2020-08-21?apiKey=XXXXXX

**Result**
`/v1/open-close/MSFT/2020-08-21` VOLUME: `36,558,537`
`/v2/aggs/ticker/MSFT/range/1/MINUTE/2020-08-21/2020-08-21` VOLUME: `32,250,609` (summed all bars)

`/v1/open-close/MSFT/2020-08-24` VOLUME: `25,660,245`
`/v2/aggs/ticker/MSFT/range/1/MINUTE/2020-08-24/2020-08-24` VOLUME: `22,503,818` (summed all bars)

**Expected Result**
When iterating over all the 1 minute bars for a given date, the volume should match the reported daily volume

Instead the iterated/summed volume is always less (for these examples), which implies there are either missing bars or the volume data is incomplete. In many cases the values align, but in a considerable number of stocks/days, the values do not align.

I found this to be the case on pretty much every symbol I checked by looking at the past 10 trading days.

**Comment by jrbell19** [comment]
This is actually expected behavior. 

It is likely that the roughly 10M difference of volume was traded on FINRA exchanges during extended hours. These trades would have updated the volume, but not the aggregate values. If an entire minute went by without an eligible trade, we do not broadcast an aggregate for that minute, therefore the volume would not be sent out. 

Unfortunately we cannot send the volume out on the next bar, because it would not reflect the previous minute incorrectly. We are searching for solutions that could solve the confusion that this causes. 

For more information on how we calculate the Aggregate, refer to this article: https://polygon.io/blog/understanding-trade-eligibility/

Hope this clears things up. Please don't hesitate to reach out with any additional questions or concerns.

**Comment by neoform** [comment]
Thanks for the explanation.

Is there a reason why you cannot send an empty bar if there was volume during that period? I assume this would mean more data transfer, but it would also increase the accuracy, and make it possible to do certain calculations that I would otherwise be unable to do without each bar's volume. 

Eg, at the moment I cannot calculate VWAP independently.

Thanks

**Comment by jrbell19** [comment]
If we sent out an empty bar, the OHLC values would all = 0, which would skew a lot of Algos. We will attempt to come up with a solution for this.

If you have any input into what you personally would like to see I would recommend opening a feature request so we can take that into account.

**Comment by neoform** [comment]
Will do, thanks.
